const cabeleireiros = [{
    id: 1,
    nome: "Ana Silva",
    foto: "./images/image-1.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.9,
    preco_medio: 150,
    endereco_estabelecimento: "Rua Flores, 123, Centro",
    servicos: ["Corte feminino", "Tintura", "Escova"],
    shortbio: "Especialista em cortes e colorações, entrego estilo e confiança com cada transformação. Dedicação e amor pela beleza em cada fio.",
    foto_1: "./imgC/img/C1.png",
    foto_2: "./imgC/img/c11.jpg",
    foto_3: "./imgC/img/c111.webp",
    foto_4: "./imgC/img/c1111.jpg"
}, {
    id: 2,
    nome: "Lucas Oliveira",
    foto: "./images/image-2.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.7,
    preco_medio: 120,
    endereco_estabelecimento: null,
    servicos: ["Corte masculino", "Penteado", "Hidratação"],
    shortbio: "Apaixonado por reinventar cabelos, minha missão é realçar a beleza única de cada cliente.",
    foto_1: "./imgC/img/c2.jpeg",
    foto_2: "./imgC/img/c22.webp",
    foto_3: "./imgC/img/c222.webp",
    foto_4: "./imgC/img/c2222.avif"
}, {
    id: 3,
    nome: "Camila Pereira",
    foto: "./images/image-3.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Estabelecimento"],
    avaliacao: 4.8,
    preco_medio: 130,
    endereco_estabelecimento: "Avenida Paulista, 200, São Paulo",
    servicos: ["Corte feminino", "Alisamento", "Mechas"],
    shortbio: "Corte e coloração impecáveis, sempre buscando tendências e inovações para deixar você incrível.",
    foto_1: "./imgC/img/c3.webp",
    foto_2: "./imgC/img/c33.jpg",
    foto_3: "./imgC/img/c333.avif",
    foto_4: "./imgC/img/c3333.jpg"
}, {
    id: 4,
    nome: "Rafael Santos",
    foto: "./images/image-5.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.6,
    preco_medio: 110,
    endereco_estabelecimento: "Rua das Palmeiras, 45, Rio de Janeiro",
    servicos: ["Corte masculino", "Escova progressiva"],
    shortbio: "Transformo cabelos com técnica e paixão. Dedico-me a garantir a sua melhor versão.",
    foto_1: "./imgC/img/c4.jpg",
    foto_2: "./imgC/img/c44.jpg",
    foto_3: "./imgC/img/c444.avif",
    foto_4: "./imgC/img/c4444.webp"
}, {
    id: 5,
    nome: "Juliana Lima",
    foto: "./images/image-4.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.9,
    preco_medio: 170,
    endereco_estabelecimento: null,
    servicos: ["Corte feminino", "Coloração", "Escova"],
    shortbio: "Corte preciso e personalizado, com foco no estilo que combina com você.",
    foto_1: "./imgC/img/c5.webp",
    foto_2: "./imgC/img/c55.jpg",
    foto_3: "./imgC/img/c555.jpg",
    foto_4: "./imgC/img/c5555.jpeg"
}, {
    id: 6,
    nome: "Mariana Souza",
    foto: "./images/image-7.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.8,
    preco_medio: 160,
    endereco_estabelecimento: "Rua Brasil, 80, Salvador",
    servicos: ["Corte infantil", "Tratamento capilar"],
    shortbio: "Criatividade e técnica se unem para transformar seu cabelo. Cada detalhe é importante.",
    foto_1: "./imgC/img/c6.webp",
    foto_2: "./imgC/img/c66.jpg",
    foto_3: "./imgC/img/c666.webp",
    foto_4: "./imgC/img/c6666.jpg"
}, {
    id: 7,
    nome: "Carlos Andrade",
    foto: "./images/image-9.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.5,
    preco_medio: 140,
    endereco_estabelecimento: null,
    servicos: ["Corte masculino", "Desenho de barba"],
    shortbio: "Especializado em cortes modernos e coloração, cuido do seu cabelo com profissionalismo.",
    foto_1: "./imgC/img/c7.webp",
    foto_2: "./imgC/img/c77.webp",
    foto_3: "./imgC/img/c777.jpg",
    foto_4: "./imgC/img/c7777.jpg"
}, {
    id: 8,
    nome: "Paula Mendes",
    foto: "./images/image-8.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.7,
    preco_medio: 130,
    endereco_estabelecimento: "Avenida Atlântica, 300, Belo Horizonte",
    servicos: ["Corte feminino", "Tintura", "Hidratação"],
    shortbio: "Ofereço um serviço que vai além de um simples corte, trazendo confiança e estilo.",
    foto_1: "./imgC/img/c8.jpeg",
    foto_2: "./imgC/img/c88.jpeg",
    foto_3: "./imgC/img/c888.jpg",
    foto_4: "./imgC/img/c8888.jpg"
}, {
    id: 9,
    nome: "Fernando Lopes",
    foto: "./images/image-10.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Estabelecimento"],
    avaliacao: 4.6,
    preco_medio: 125,
    endereco_estabelecimento: "Rua Amazonas, 50, Curitiba",
    servicos: ["Corte masculino", "Penteado"],
    shortbio: "Corte, coloração e estilo com perfeição. Cada cliente merece o melhor.",
    foto_1: "./imgC/img/c9.jpg",
    foto_2: "./imgC/img/c99.jpeg",
    foto_3: "./imgC/img/c999.jpg",
    foto_4: "./imgC/img/c9999.webp"
}, {
    id: 10,
    nome: "Sofia Ribeiro",
    foto: "./images/image-7.png",
    especialidade: "Cabeleireiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.9,
    preco_medio: 180,
    endereco_estabelecimento: null,
    servicos: ["Corte feminino", "Alisamento", "Escova"],
    shortbio: "Meu trabalho é transformar cabelos, sempre focado na sua satisfação e estilo.",
    foto_1: "./imgC/img/c10.png",
    foto_2: "./imgC/img/c100.jpeg",
    foto_3: "./imgC/img/c1000.jpeg",
    foto_4: "./imgC/img/c10000.jpeg"
}]

const barbeiros = [{
    id: 11,
    nome: "João Fernandes",
    foto: "./images/image-11.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.8,
    preco_medio: 90,
    endereco_estabelecimento: "Rua dos Anjos, 101, São Paulo",
    servicos: ["Corte masculino", "Barba"],
    shortbio: "Expert em cortes e barba, dedico-me a deixar você impecável com técnicas tradicionais e modernas.",
    foto_1: "./imgb/1.jpg",
    foto_2: "./imgb/111.webp",
    foto_3: "./imgb/1111.jpg",
    foto_4: "./imgb/Barbeiro1.jpg"
}, {
    id: 12,
    nome: "Diego Santos",
    foto: "./images/image-55.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.9,
    preco_medio: 100,
    endereco_estabelecimento: null,
    servicos: ["Corte masculino", "Sobrancelha"],
    shortbio: "Cortes e barbas sob medida, com atenção a cada detalhe. Seu visual é minha prioridade.",
    foto_1: "./imgb/22.jpg",
    foto_2: "./imgb/222.jpg",
    foto_3: "./imgb/2222.jpg",
    foto_4: "./imgb/Barbeiro 2.webp"
}, {
    id: 13,
    nome: "Renato Lima",
    foto: "./images/image-16.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Estabelecimento"],
    avaliacao: 4.7,
    preco_medio: 85,
    endereco_estabelecimento: "Rua das Flores, 300, Rio de Janeiro",
    servicos: ["Corte masculino", "Desenho de barba"],
    shortbio: "Barbearia é arte, e meu trabalho é esculpir o melhor visual para você.",
    foto_1: "./imgb/3.jpg",
    foto_2: "./imgb/333.jpg",
    foto_3: "./imgb/3333.jpg",
    foto_4: "./imgb/Barbeiro 3.jpg"
}, {
    id: 14,
    nome: "Eduardo Mendes",
    foto: "./images/image-321.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.6,
    preco_medio: 95,
    endereco_estabelecimento: null,
    servicos: ["Corte masculino", "Barba"],
    shortbio: "Domino técnicas clássicas e contemporâneas para cortes e barbas de alto nível.",
    foto_1: "./imgb/44.jpg",
    foto_2: "./imgb/444.webp",
    foto_3: "./imgb/4444.jpg",
    foto_4: "./imgb/Barbeiro 4.jpeg"
}, {
    id: 15,
    nome: "Matheus Souza",
    foto: "./images/image-400.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.9,
    preco_medio: 110,
    endereco_estabelecimento: "Avenida Brasil, 200, Belo Horizonte",
    servicos: ["Corte masculino", "Coloração de barba"],
    shortbio: "Cortes e barbas feitos com precisão e estilo. Dedicação total para cada cliente.",
    foto_1: "./imgb/55.jpg",
    foto_2: "./imgb/555.webp",
    foto_3: "./imgb/5555.jpg",
    foto_4: "./imgb/Barbeiro 5.jpeg"

}, {
    id: 16,
    nome: "Ricardo Alves",
    foto: "./images/image-350.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Estabelecimento"],
    avaliacao: 4.8,
    preco_medio: 105,
    endereco_estabelecimento: "Rua Minas Gerais, 77, Salvador",
    servicos: ["Corte masculino", "Desenho de barba"],
    shortbio: "Especialista em detalhes, faço cortes e barbas que elevam sua confiança.",
    foto_1: "./imgb/6.jpeg",
    foto_2: "./imgb/66.jpg",
    foto_3: "./imgb/6666.webp",
    foto_4: "./imgb/Barbeiro 6.webp"
}, {
    id: 17,
    nome: "Felipe Costa",
    foto: "./images/image-27.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.7,
    preco_medio: 100,
    endereco_estabelecimento: null,
    servicos: ["Corte masculino", "Sobrancelha"],
    shortbio: "Com estilo e técnica, ofereço um serviço de barbearia premium no conforto da sua casa.",
    foto_1: "./imgb/77.webp",
    foto_2: "./imgb/777.jpg",
    foto_3: "./imgb/7777.jpg",
    foto_4: "./imgb/barbeiro 7.jpg"
}, {
    id: 18,
    nome: "Thiago Gomes",
    foto: "./images/image-123.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.5,
    preco_medio: 90,
    endereco_estabelecimento: "Rua Nova, 102, Recife",
    servicos: ["Corte masculino", "Barba"],
    shortbio: "Cortes masculinos e barbas personalizadas com paixão e precisão.",
    foto_1: "./imgb/8.jpeg",
    foto_2: "./imgb/888.jpg",
    foto_3: "./imgb/8888.jpg",
    foto_4: "./imgb/Barbeiro 8.webp"
}, {
    id: 19,
    nome: "Gabriel Martins",
    foto: "./images/image-66.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.9,
    preco_medio: 110,
    endereco_estabelecimento: null,
    servicos: ["Corte masculino", "Coloração de barba"],
    shortbio: "O visual perfeito começa com um corte impecável. Faço questão de entregar sempre o melhor.",
    foto_1: "./imgb/9.webp",
    foto_2: "./imgb/999.jpg",
    foto_3: "./imgb/9999.jpg",
    foto_4: "./imgb/3-3-jpg.webp"
}, {
    id: 20,
    nome: "André Pereira",
    foto: "./images/cafumango.png",
    especialidade: "Barbeiro",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.6,
    preco_medio: 80,
    endereco_estabelecimento: "Rua das Palmeiras, 12, Fortaleza",
    servicos: ["Corte masculino", "Desenho de barba"],
    shortbio: "Minhas técnicas garantem unhas bonitas e bem cuidadas, sempre com foco em detalhes.",
    foto_1: "./imgb/10.jpg",
    foto_2: "./imgb/100.webp",
    foto_3: "./imgb/1000.jpg",
    foto_4: "./imgb/barbeiro 10.webp"
}];

const manicures = [{
        id: 21,
        nome: "Beatriz Costa",
        foto: "./images/image-13.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente", "Estabelecimento"],
        avaliacao: 4.9,
        preco_medio: 60,
        endereco_estabelecimento: "Rua das Rosas, 30, Rio de Janeiro",
        servicos: ["Unhas decoradas", "Spa das mãos"],
        shortbio: "Unhas bem feitas são meu foco. Dedico-me a oferecer o melhor para você.",
        foto_1: "./imgM/M1.jpg",
        foto_2: "./imgM/M11.jpg",
        foto_3: "./imgM/M111.webp",
        foto_4: "./imgM/M1111.jpg"
    }, {
        id: 22,
        nome: "Larissa Souza",
        foto: "./images/elizabete.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente"],
        avaliacao: 4.8,
        preco_medio: 55,
        endereco_estabelecimento: null,
        servicos: ["Cutilagem", "Esmaltação"],
        shortbio: "Cuido de suas unhas com amor e técnica. Dedicação para um resultado impecável.",
        foto_1: "./imgM/M2.jpg",
        foto_2: "./imgM/M22.jpg",
        foto_3: "./imgM/M222.jpg",
        foto_4: "./imgM/M2222.jpg"
    }, {
        id: 23,
        nome: "Patrícia Almeida",
        foto: "./images/image-17.png",
        especialidade: "Manicure",
        local_atendimento: ["Estabelecimento"],
        avaliacao: 4.7,
        preco_medio: 65,
        endereco_estabelecimento: "Avenida Central, 100, Belo Horizonte",
        servicos: ["Alongamento de unhas", "Esmaltação"],
        shortbio: "Trabalho com precisão e criatividade para deixar suas unhas perfeitas.",
        foto_1: "./imgM/M3.webp",
        foto_2: "./imgM/M33.jpg",
        foto_3: "./imgM/M333.avif",
        foto_4: "./imgM/M3333.jpg"
    },

    {
        id: 24,
        nome: "Marcela Pereira",
        foto: "./images/carlinha.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente"],
        avaliacao: 4.9,
        preco_medio: 70,
        endereco_estabelecimento: null,
        servicos: ["Cutilagem", "Unhas de gel"],
        shortbio: "Especialista em unhas impecáveis, trago cuidado e beleza para suas mãos.",
        foto_1: "./imgM/M4.webp",
        foto_2: "./imgM/M44.jpeg",
        foto_3: "./imgM/M444.jpeg",
        foto_4: "./imgM/M4444.jpg"
    },

    {
        id: 25,
        nome: "Renata Lima",
        foto: "./images/cristiane.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente", "Estabelecimento"],
        avaliacao: 4.6,
        preco_medio: 60,
        endereco_estabelecimento: "Rua das Acácias, 45, São Paulo",
        servicos: ["Esmaltação", "Spa dos pés"],
        shortbio: "Minha paixão é transformar unhas com cuidado e criatividade. Seu bem-estar é minha prioridade.",
        foto_1: "./imgM/M5.avif",
        foto_2: "./imgM/M55.png",
        foto_3: "./imgM/M555.jpg",
        foto_4: "./imgM/M5555.webp"
    }, {
        id: 26,
        nome: "Jéssica Martins",
        foto: "./images/image-23.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente"],
        avaliacao: 4.7,
        preco_medio: 50,
        endereco_estabelecimento: null,
        servicos: ["Cutilagem", "Unhas postiças"],
        shortbio: "Unhas impecáveis, com atenção a cada detalhe. Dedicação total ao seu estilo.",
        foto_1: "./imgM/M6.jpg",
        foto_2: "./imgM/M66.jpg",
        foto_3: "./imgM/M666.webp",
        foto_4: "./imgM/M6666.webp"
    }, {
        id: 27,
        nome: "Alessandra Mendes",
        foto: "./images/image-24.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente", "Estabelecimento"],
        avaliacao: 4.8,
        preco_medio: 75,
        endereco_estabelecimento: "Rua São João, 120, Curitiba",
        servicos: ["Unhas decoradas", "Cutilagem"],
        shortbio: "Especialista em manicure, ofereço um serviço focado no cuidado e na beleza das unhas.",
        foto_1: "./imgM/M7.jpeg",
        foto_2: "./imgM/M77.jpg",
        foto_3: "./imgM/M777.jpg",
        foto_4: "./imgM/M7777.jpg"
    }, {
        id: 28,
        nome: "Sabrina Oliveira",
        foto: "./images/sabrina.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente"],
        avaliacao: 4.5,
        preco_medio: 65,
        endereco_estabelecimento: null,
        servicos: ["Unhas de gel", "Spa dos pés"],
        shortbio: "Transformo suas unhas com cuidado e estilo, garantindo um acabamento perfeito.",
        foto_1: "./imgM/M8.jpg",
        foto_2: "./imgM/M88.webp",
        foto_3: "./imgM/M888.jpg",
        foto_4: "./imgM/M8888.jpg"
    }, {
        id: 29,
        nome: "Tatiane Ribeiro",
        foto: "./images/image-39.png",
        especialidade: "Manicure",
        local_atendimento: ["Estabelecimento"],
        avaliacao: 4.7,
        preco_medio: 60,
        endereco_estabelecimento: "Avenida Paulista, 300, São Paulo",
        servicos: ["Cutilagem", "Esmaltação"],
        shortbio: "Minhas técnicas garantem unhas bonitas e bem cuidadas, sempre com foco em detalhes.",
        foto_1: "./imgM/M9.jpg",
        foto_2: "./imgM/M99.jpg",
        foto_3: "./imgM/M999.webp",
        foto_4: "./imgM/M9999.jpg"
    }, {
        id: 30,
        nome: "Monica Ferreira",
        foto: "./images/image-40.png",
        especialidade: "Manicure",
        local_atendimento: ["Casa do cliente", "Estabelecimento"],
        avaliacao: 4.9,
        preco_medio: 70,
        endereco_estabelecimento: "Rua Rio Branco, 80, Porto Alegre",
        servicos: ["Alongamento de unhas", "Esmaltação"],
        shortbio: "Minhas técnicas garantem unhas bonitas e bem cuidadas, sempre com foco em detalhes.",
        foto_1: "./imgM/M10.webp",
        foto_2: "./imgM/M100.webp",
        foto_3: "./imgM/M1000.jpg",
        foto_4: "./imgM/M10000.webp"

    }
]

const maquiadores = [{
    id: 31,
    nome: "Clara Souza",
    foto: "./images/image-29.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.9,
    preco_medio: 150,
    endereco_estabelecimento: "Rua Sete de Setembro, 110, São Paulo",
    servicos: ["Maquiagem para festas", "Maquiagem artística"],
    shortbio: "Transformo beleza em arte, criando looks únicos que realçam o melhor em você.",
    foto_1: "./imgMAQ/m1.jpg",
    foto_2: "./imgMAQ/m11.jpeg",
    foto_3: "./imgMAQ/m111.jpg",
    foto_4: "./imgMAQ/m1111.jpg"
}, {
    id: 32,
    nome: "Bruno Santos",
    foto: "./images/image-66.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.8,
    preco_medio: 140,
    endereco_estabelecimento: null,
    servicos: ["Maquiagem social", "Maquiagem para noivas"],
    shortbio: "Cada rosto é uma tela, e meu trabalho é destacar sua beleza com perfeição.",
    foto_1: "./imgMAQ/m2.jpeg",
    foto_2: "./imgMAQ/m22.avif",
    foto_3: "./imgMAQ/m222.jpg",
    foto_4: "./imgMAQ/m2222.jpg"
}, {
    id: 33,
    nome: "Júlia Ferreira",
    foto: "./images/image-36.png",
    especialidade: "Maquiador",
    local_atendimento: ["Estabelecimento"],
    avaliacao: 4.7,
    preco_medio: 130,
    endereco_estabelecimento: "Avenida Brasil, 500, Rio de Janeiro",
    servicos: ["Maquiagem profissional", "Maquiagem artística"],
    shortbio: "Maquiagem é meu dom, e cada cliente merece um look personalizado e impecável.",
    foto_1: "./imgMAQ/m3.jpg",
    foto_2: "./imgMAQ/m33.jpg",
    foto_3: "./imgMAQ/m333.jpg",
    foto_4: "./imgMAQ/m3333.jpg"
}, {
    id: 34,
    nome: "Vanessa Lima",
    foto: "./images/image-35.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.6,
    preco_medio: 120,
    endereco_estabelecimento: null,
    servicos: ["Maquiagem social", "Maquiagem para festas"],
    shortbio: "Minha missão é realçar a sua beleza natural com técnicas sofisticadas de maquiagem.",
    foto_1: "./imgMAQ/m4.webp",
    foto_2: "./imgMAQ/m44.jpeg",
    foto_3: "./imgMAQ/m444.jpg",
    foto_4: "./imgMAQ/m4444.jpg"
}, {
    id: 35,
    nome: "Daniela Oliveira",
    foto: "./images/image-42.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.8,
    preco_medio: 160,
    endereco_estabelecimento: "Rua das Palmeiras, 50, Porto Alegre",
    servicos: ["Maquiagem artística", "Maquiagem para noivas"],
    shortbio: "Maquiagem personalizada e profissional, sempre focada em destacar o que você tem de melhor.",
    foto_1: "./imgMAQ/m5.jpg",
    foto_2: "./imgMAQ/m55.jpg",
    foto_3: "./imgMAQ/m555.jpg",
    foto_4: "./imgMAQ/m5555.jpeg"
}, {
    id: 36,
    nome: "Fernanda Mendes",
    foto: "./images/image-34.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.7,
    preco_medio: 150,
    endereco_estabelecimento: null,
    servicos: ["Maquiagem profissional", "Maquiagem para festas"],
    shortbio: "Minha paixão é criar looks que elevam sua confiança e destacam sua beleza única.",
    foto_1: "./imgMAQ/m6.jpg",
    foto_2: "./imgMAQ/m66.jpg",
    foto_3: "./imgMAQ/m666.jpeg",
    foto_4: "./imgMAQ/m6666.jpg"
}, {
    id: 37,
    nome: "Isabela Ribeiro",
    foto: "./images/carpenter.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.9,
    preco_medio: 170,
    endereco_estabelecimento: "Avenida Paulista, 800, São Paulo",
    servicos: ["Maquiagem social", "Maquiagem para noivas"],
    shortbio: "Trago técnicas avançadas de maquiagem para garantir que você se sinta incrível.",
    foto_1: "./imgMAQ/m7.jpeg",
    foto_2: "./imgMAQ/m77.jpeg",
    foto_3: "./imgMAQ/m777.webp",
    foto_4: "./imgMAQ/m7777.webp"
}, {
    id: 38,
    nome: "fernanda Silva",
    foto: "./images/bruna.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente"],
    avaliacao: 4.6,
    preco_medio: 140,
    endereco_estabelecimento: null,
    servicos: ["Maquiagem para festas", "Maquiagem artística"],
    shortbio: "Cada cliente é único, e minha maquiagem reflete isso com perfeição e cuidado.",
    foto_1: "./imgMAQ/m8.jpg",
    foto_2: "./imgMAQ/m88.jpg",
    foto_3: "./imgMAQ/m888.jpg",
    foto_4: "./imgMAQ/m8888.jpeg"
}, {
    id: 39,
    nome: "Camila Lopes",
    foto: "./images/image-39.png",
    especialidade: "Maquiador",
    local_atendimento: ["Estabelecimento"],
    avaliacao: 4.7,
    preco_medio: 130,
    endereco_estabelecimento: "Rua das Flores, 60, Curitiba",
    servicos: ["Maquiagem profissional", "Maquiagem para festas"],
    shortbio: "Especialista em maquiagem para ocasiões especiais, com foco em realçar sua beleza natural.",
    foto_1: "./imgMAQ/m9.avif",
    foto_2: "./imgMAQ/m99.jpg",
    foto_3: "./imgMAQ/m999.avif",
    foto_4: "./imgMAQ/m9999.jpg"
}, {
    id: 40,
    nome: "Gabriela Lima",
    foto: "./images/image-22.png",
    especialidade: "Maquiador",
    local_atendimento: ["Casa do cliente", "Estabelecimento"],
    avaliacao: 4.9,
    preco_medio: 160,
    endereco_estabelecimento: "Rua São João, 120, Salvador",
    servicos: ["Maquiagem social", "Maquiagem artística"],
    shortbio: "Dedico-me a criar maquiagens que te façam sentir confiante e radiante.",
    foto_1: "./imgMAQ/m10.jpg",
    foto_2: "./imgMAQ/m100.jpeg",
    foto_3: "./imgMAQ/m1000.webp",
    foto_4: "./imgMAQ/m10000.webp"
}]